name: node

on:
  pull_request:
    paths-ignore:
      - "**.md"
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Run Rome CI
        run: npx rome ci .

      - name: Check build
        run: yarn build
